export const jadComparisons = [
  {
    slug: "home",
    name: "Homepage",
    title: "From a Pacific getaway to a clear business proposition.",
    before: "A holiday-led carousel and a broad invitation to explore the Pacific.",
    after: "JAD’s Suva office, its travel heritage and a direct focus on corporate and group journeys.",
    reason: "The opening message needed to reflect the organisational travel work JAD actually handles.",
    benefit: "Corporate clients and group leaders can recognise the relevant service before exploring further.",
  },
  {
    slug: "about",
    name: "About JAD",
    title: "From a brand illustration to the people behind the service.",
    before: "A stylised globe, broad company statements and a brief description of JAD’s experience.",
    after: "Real team photography, a clearer company history and consultant profiles with their areas of expertise.",
    reason: "An established local agency has a stronger story to tell through its people and experience.",
    benefit: "Customers can understand who they will deal with and what knowledge the team brings.",
  },
  {
    slug: "corporate",
    name: "Corporate travel",
    title: "From broad promises to a practical coordination process.",
    before: "The page led with policy automation and savings claims alongside general corporate-travel messaging.",
    after: "The copy describes policy-aligned coordination, visible travel options, internal approvals and experienced consultant support.",
    reason: "The service description needed to explain the agency’s role without implying software capabilities or guaranteed savings.",
    benefit: "Administrators and approvers get a clearer picture of how JAD can support their travel requests.",
  },
  {
    slug: "medical",
    name: "Medical travel",
    title: "A clearer description of travel-logistics support.",
    before: "A compact illustrated banner and service cards used broad language around medical clearance and special assistance.",
    after: "A stronger page introduction and more careful wording about itineraries, documentation and assistance requests, including provider confirmation.",
    reason: "Medical travel needs clear boundaries between agency coordination and decisions made by airlines or other providers.",
    benefit: "Travellers and families can understand the help available and the approvals their journey may still require.",
  },
  {
    slug: "contact",
    name: "Contact and enquiries",
    title: "Keeping the enquiry form and making the local team visible.",
    before: "An existing enquiry form sat beside office details and a map area that did not render in the supplied capture.",
    after: "The contact page leads with JAD’s actual Suva office and pairs the enquiry form with photographs of its front-desk consultants.",
    reason: "The enquiry experience needed to feel connected to the people and place behind the business.",
    benefit: "Visitors can see the local team they are contacting while retaining a familiar way to send an enquiry.",
  },
];
